### ISSUE TITLE
Multiprocessing/threading RuntimeError on Windows 10

### ISSUE THREAD

**Issue by mshumko** [ucalgary-aurora/themis-imager-readfile#4]
**Describe the bug**
THEMIS image loader crashes due to a threading or multiprocessing bug on Windows 10. This bug does not affect Ubuntu.

```python
Exception has occurred: RuntimeError

        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
  File "C:\Users\xyz\Documents\research\aurora-asi-lib\asilib\asi\themis.py", line 467, in _load_pgm
    images, meta, problematic_file_list = themis_imager_readfile.read(str(path), workers=1)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**To Reproduce**
```python
import themis_imager_readfile
themis_imager_readfile.read('20170915_0232_rank_themis12_full.pgm.gz', workers=1)
```

**Expected behavior**
Data loaded.

**Environemnt:**
```python
>>> import sys, themis_imager_readfile, platform; print(themis_imager_readfile.__version__); print(sys.version); print(platform.platform())
1.0.11
3.11.3 | packaged by Anaconda, Inc. | (main, Apr 19 2023, 23:46:34) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.19044-SP0
```

**Comment by dchaddock** [comment]
Thanks Mike. We noticed this last week and it seems to be due to something about not putting the read call in a main() method. We'll have a look at it and see where the issue is.

**Comment by dchaddock** [comment]
Just an update - this is a known thing with multiprocessing, where usage of `__main__()` is required. We will see what we can do to put a user warning in to help.

**Comment by dchaddock** [comment]
A note has been put in to the Readme. Unfortunately, there isn't a way to detect this programmatically so the readme and this issue ticket will have to be enough for others who run into the issue.

**Comment by mshumko** [comment]
@dchaddock, wrapping my code with a

```python
if __name__ == '__main__':
```
did the trick. Does this mean that all users of `aurora-asi-lib` need to wrap their code this way too? Or is there an alternative way to call `themis_imager_readfile` that avoids multiprocessing altogether? The latter option is the one that I'm perusing in `aurora-asi-lib`.
